### ISSUE TITLE
2.0.0版本启动一段时间就挂了

### ISSUE THREAD

**Issue by yedw** [HashDataInc/bireme#113]
20:39:18 ERROR Maxwell-maxwell1-test-1 - Dispatch failed. Message: Transform failed.

20:39:18 ERROR Maxwell-maxwell1-test-1 - Stack Trace: 
cn.hashdata.bireme.BiremeException: Transform failed.

        at cn.hashdata.bireme.Dispatcher.dispatch(Dispatcher.java:60) ~[bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine.startDispatch(PipeLine.java:150) [bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine.executePipeline(PipeLine.java:106) [bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine.call(PipeLine.java:87) [bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine.call(PipeLine.java:39) [bireme-2.0.0-alpha-1.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at cn.hashdata.bireme.pipeline.MaxwellPipeLine$MaxwellTransformer$MaxwellRecord.<init>(MaxwellPipeLine.java:135) ~[bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.MaxwellPipeLine$MaxwellTransformer.transform(MaxwellPipeLine.java:89) ~[bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.KafkaPipeLine$KafkaTransformer.fillRowSet(KafkaPipeLine.java:113) ~[bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine$Transformer.call(PipeLine.java:273) ~[bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine$Transformer.call(PipeLine.java:248) ~[bireme-2.0.0-alpha-1.jar:?]
        ... 4 more
20:39:18 INFO  Scheduler - All pipeline stop.
cn.hashdata.bireme.BiremeException: Transform failed.

**Comment by wangzw** [comment]
Which database are you syncing from?

**Comment by yedw** [comment]
mysql
