### ISSUE TITLE
bire2.0支持mongo配置吗

### ISSUE THREAD

**Issue by jameswangcnbj** [HashDataInc/bireme#126]
源mongdodb，目的greenplum
config.properties

> data_source = debezium
debezium.type = debezium
debezium.namespace = mongotest
debezium.kafka.server = 127.0.0.1:9092
debezium.kafka.groupid = bireme

 数据已经在kafka中，topic是mongotest.case.test
启动报错，错误信息

> cn.hashdata.bireme.BiremeException: error occurs in this way!
	at cn.hashdata.bireme.Bireme.getTableInfo(Bireme.java:117) ~[bireme-2.0.0-alpha-1.jar:?]
	at cn.hashdata.bireme.Bireme.start(Bireme.java:283) [bireme-2.0.0-alpha-1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:243) [commons-daemon-1.0.15.jar:1.0.15]
Caused by: cn.hashdata.bireme.BiremeException: Greenplum table and MySQL table size are inconsistent!
	at cn.hashdata.bireme.GetPrimaryKeys.getPrimaryKeys(GetPrimaryKeys.java:73) ~[bireme-2.0.0-alpha-1.jar:?]
	at cn.hashdata.bireme.Bireme.getTableInfo(Bireme.java:114) ~[bireme-2.0.0-alpha-1.jar:?]
	... 6 more

奇怪的是我没有mysql数据源，报错怎么会提示mysql表大小不一致

**Comment by jameswangcnbj** [comment]
@wangzw

**Comment by wangzw** [comment]
理论上是支持的，但是没有测试过mongodb。

**Comment by jameswangcnbj** [comment]
奇怪怎么报错mysql呢，另外地如何让日志更详细点，目前不确定哪个地方配置出了问题

**Comment by wangzw** [comment]
这个报错本身应该是有些问题。报错的意思是说，你GP表的列数量，和kafka里数据的列数量不一样。

**Comment by jameswangcnbj** [comment]
对mongo类型表移动到gp，表如何创建呢，我目前在gp中只是创建了一个jsonb类型的不同名的列，这是导致问题的原因吗，那gp表如何对应到mongo的表呢，给个提示
