### ISSUE TITLE
postgres执行DELETE操作时brieme报错：cn.hashdata.bireme.BiremeException: Transform failed.

### ISSUE THREAD

**Issue by LittleWuCoding** [HashDataInc/bireme#131]
postgres执行DELETE操作时brieme报以下错误：
```
16:47:20 ERROR Debezium-debezium1-debezium1.public.test_s - Stack Trace:
cn.hashdata.bireme.BiremeException: Transform failed.

        at cn.hashdata.bireme.Dispatcher.dispatch(Dispatcher.java:60) ~[bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine.startDispatch(PipeLine.java:150) [bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine.executePipeline(PipeLine.java:106) [bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine.call(PipeLine.java:87) [bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine.call(PipeLine.java:39) [bireme-2.0.0-alpha-1.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
        at java.io.StringReader.<init>(StringReader.java:50) ~[?:1.8.0_212]
        at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[gson-2.8.0.jar:?]
        at cn.hashdata.bireme.pipeline.DebeziumPipeLine$DebeziumTransformer.transform(DebeziumPipeLine.java:89) ~[bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.KafkaPipeLine$KafkaTransformer.fillRowSet(KafkaPipeLine.java:113) ~[bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine$Transformer.call(PipeLine.java:273) ~[bireme-2.0.0-alpha-1.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine$Transformer.call(PipeLine.java:248) ~[bireme-2.0.0-alpha-1.jar:?]
        ... 4 more

```
请问这是bug还是怎么回事？
使用的是：postgres + wal2json + debezium + kafka + brieme + greenplum
postgres用的pg10，使用插件wal2json
greenplum使用的是6.4版本
bireme使用的1.0版本和2.9-alpha版本都报错

**Comment by cobolbaby** [comment]
The payload structure of `DELETE` event  is `null` when you config as below:

```
"transforms": "unwrap",
"transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState"
```
