### ISSUE TITLE
Failed to start bireme service

### ISSUE THREAD

**Issue by SbloodyS** [HashDataInc/bireme#27]
启动bireme 失败，日志如下，请问该如何解决呢？

12:47:26 FATAL Bireme - Stack Trace:
java.lang.NullPointerException: null
        at cn.hashdata.bireme.Config.fetchProviderAndTableMap(Config.java:168) ~[bireme-1.0.0.jar:?]
        at cn.hashdata.bireme.Config.dataSourceConfig(Config.java:150) ~[bireme-1.0.0.jar:?]
        at cn.hashdata.bireme.Config.<init>(Config.java:83) ~[bireme-1.0.0.jar:?]
        at cn.hashdata.bireme.Bireme.parseCommandLine(Bireme.java:88) ~[bireme-1.0.0.jar:?]
        at cn.hashdata.bireme.Bireme.init(Bireme.java:219) [bireme-1.0.0.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
        at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:207) [commons-daemon-1.0.15.jar:1.0.15]
12:47:26 INFO  Bireme - start Bireme daemon.
12:47:26 INFO  Bireme - Start getting metadata of target tables from target database.
12:47:48 INFO  Bireme - initialize Bireme daemon
12:47:48 FATAL Bireme - start failed. Message: null.

**Comment by wangzw** [comment]
You do not specify the data source's type

**Comment by SbloodyS** [comment]
# target database where the data will sync into.
target.url = jdbc:postgresql:/10.1.2.50:5432/db_replica
target.user = usr_replica
target.passwd = replica

# data source name list, separated by comma.
data_source = mysql

# data source "mysql1" type
mysql.type = maxwell
# kafka server which maxwell write binlog into.
mysql.kafka.server = 10.1.2.53:9092
# kafka topic which maxwell write binlog into.
mysql.kafka.topic = mytopic
# kafka groupid used for consumer.
mysql.kafka.groupid = bireme


请问是哪错了呢？

**Comment by SbloodyS** [comment]
解决啦，谢谢~

**Comment by tangbinbinyes** [comment]
请问是如何和解决的，我这里这是启动报错，java.lang.NullPointerException
