### ISSUE TITLE
NullPointerException when getConnection

### ISSUE THREAD

**Issue by DongJianzhi0223** [HashDataInc/bireme#35]
13:29:53 INFO  Maxwell-mysql-edad-earth_market-0 - Loader for public.tcustomer_service failed. Message: Loader failed. .
13:29:53 INFO  Maxwell-mysql-edad-earth_market-0 - Stack Trace: 
cn.hashdata.bireme.BiremeException: Loader failed. 
        at cn.hashdata.bireme.RowCache.startLoad(RowCache.java:147) ~[bireme-1.0.0.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine.call(PipeLine.java:141) [bireme-1.0.0.jar:?]
        at cn.hashdata.bireme.pipeline.PipeLine.call(PipeLine.java:39) [bireme-1.0.0.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at cn.hashdata.bireme.ChangeLoader.getConnection(ChangeLoader.java:176) ~[bireme-1.0.0.jar:?]
        at cn.hashdata.bireme.ChangeLoader.call(ChangeLoader.java:111) ~[bireme-1.0.0.jar:?]
        at cn.hashdata.bireme.ChangeLoader.call(ChangeLoader.java:42) ~[bireme-1.0.0.jar:?]
        ... 4 more

**Comment by wangzw** [comment]
https://github.com/HashDataInc/bireme/blob/e5e388911fe0dbddb14b896a3ba398ba0d0241f1/src/main/java/cn/hashdata/bireme/ChangeLoader.java#L201

Should check stop flag and return

**Comment by ZGhey** [comment]
I have a same issuse, but i using code version is this picture, please told me should i do.
![image](https://user-images.githubusercontent.com/12210539/33652412-539f004a-daa4-11e7-9bd9-c30c0ecbbf20.png)

**Comment by wangzw** [comment]
Should check if connection is null and return if it is.
