### ISSUE TITLE
bireme启动后,1分钟左右就出现假死情况,日志没有记录任何错误

### ISSUE THREAD

**Issue by jinxiaoxin** [HashDataInc/bireme#47]
配置了50张表，bireme启动后，1分钟之内就出现假死。无任何操作，无任何报错
有遇到过这种情况的吗？

**Comment by wangzw** [comment]
Please check if there is active load query in database first. And then check loading status with rest or jmx.

**Comment by jinxiaoxin** [comment]
@wangzw     rest api   ip:8080/mysql     
result:
![image](https://user-images.githubusercontent.com/26498890/34030994-57cc481e-e1aa-11e7-8136-833fa3d60f15.png)

 rest api   ip:8080/
 result:
![image](https://user-images.githubusercontent.com/26498890/34031010-69995f78-e1aa-11e7-8eed-48348cf7479a.png)

**Comment by wangzw** [comment]
Which version of bireme are you using?

**Comment by jinxiaoxin** [comment]
@wangzw   version: Release v1.0

**Comment by wangzw** [comment]
Have you checked if binlog data has been produced into kafka?

**Comment by jinxiaoxin** [comment]
一直实时监控的，确实生产到kafka了

**Comment by jinxiaoxin** [comment]
@wangzw 发现我只要是 在bireme里面配置的表多了，就会出现此问题，，例如 kafka里面只有5张表的数据，而bireme里面配置50张表，就会出问题。是不是需要合理调节下参数？

**Comment by wangzw** [comment]
@jinxiaoxin Thanks for your information.

It would be better to enable TRACE level logging for bireme in log2j.xml.

**Comment by wangzw** [comment]
@Rucfisher What if the topic we want to subscribe does not exist? Need more investigation.

**Comment by jinxiaoxin** [comment]
我之前都用log4j，对log2j不熟悉，把这里改成trace级别就可以吧？
![image](https://user-images.githubusercontent.com/26498890/34097114-d8621ade-e412-11e7-83de-93bb054a9797.png)

**Comment by RebeccaZxy** [comment]
@jinxiaoxin 是的，level改成trace就可以。

**Comment by jinxiaoxin** [comment]
@RebeccaZxy 改了之后，还是跟以前以前，没有报错信息，假死状态。。

**Comment by wangzw** [comment]
@jinxiaoxin Please also change the root level of log to trace level and try again.

**Comment by wangzw** [comment]
@jinxiaoxin It is also helpful to print stack of bireme using command line `jstack`

**Comment by jinxiaoxin** [comment]
@wangzw   bireme.out还是没有error,倒是bireme.err里面多了一堆信息，但是也没有error

**Comment by wangzw** [comment]
Any message would help. Please paste to this issue or mail me by email. `jstack` information would be also useful.

**Comment by jinxiaoxin** [comment]
@wangzw 
jstacj info：
[jstack_message.txt](https://github.com/HashDataInc/bireme/files/1570538/jstack_message.txt)

**Comment by wangzw** [comment]
```

"Provider mysql" #38 prio=5 os_prio=0 tid=0x0000000001e16000 nid=0x8e9 waiting on condition [0x00007fefd4a3e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000003cfd06170> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:385)
	at cn.hashdata.bireme.provider.KafkaProvider.call(KafkaProvider.java:161)
	at cn.hashdata.bireme.provider.KafkaProvider.call(KafkaProvider.java:35)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000003cfc967e8> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Dispatcher" #37 prio=5 os_prio=0 tid=0x0000000001d0d800 nid=0x8e8 waiting for monitor entry [0x00007fefd4d3e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at cn.hashdata.bireme.RowCache.createBatch(RowCache.java:91)
	- waiting to lock <0x00000003cfe7c4e0> (a cn.hashdata.bireme.RowCache)
	at cn.hashdata.bireme.RowCache.addRows(RowCache.java:62)
	at cn.hashdata.bireme.Dispatcher.insertRowSet(Dispatcher.java:139)
	at cn.hashdata.bireme.Dispatcher.checkTansformResults(Dispatcher.java:124)
	at cn.hashdata.bireme.Dispatcher.call(Dispatcher.java:73)
	at cn.hashdata.bireme.Dispatcher.call(Dispatcher.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000003cfce25f0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"TaskGenerator" #36 prio=5 os_prio=0 tid=0x0000000001d0b800 nid=0x8e7 waiting on condition [0x00007fefd4e40000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000003cfe7c768> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:385)
	at cn.hashdata.bireme.RowCache.createBatch(RowCache.java:116)
	- locked <0x00000003cfe7c4e0> (a cn.hashdata.bireme.RowCache)
	at cn.hashdata.bireme.RowCache.fetchBatch(RowCache.java:130)
	at cn.hashdata.bireme.TaskGenerator.generateMergeTask(TaskGenerator.java:96)
	at cn.hashdata.bireme.TaskGenerator.call(TaskGenerator.java:63)
	at cn.hashdata.bireme.TaskGenerator.call(TaskGenerator.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000003cfd54b30> (a java.util.concurrent.ThreadPoolExecutor$Worker)


```

Seems like a dead lock

**Comment by jinxiaoxin** [comment]
emmmmm,这如何解决了。。。

**Comment by wangzw** [comment]
Remove this line may work. And we will finally fix this issue in 2.0 release.

https://github.com/HashDataInc/bireme/blob/e5e388911fe0dbddb14b896a3ba398ba0d0241f1/src/main/java/cn/hashdata/bireme/RowCache.java#L130

**Comment by jinxiaoxin** [comment]
这段代码移除之后  是一条一条的  copy了吗？没有merge了？

**Comment by wangzw** [comment]
Nope, still in batch.

**Comment by jinxiaoxin** [comment]
1、注释掉了createBatch();   还是同样的情况，kafka数据堆积过多，就会导致1分钟之内就会假死。
2、为什么我的HTTP服务器一直报500错误
![image](https://user-images.githubusercontent.com/26498890/34195377-35f11ffc-e598-11e7-99fd-06d082defa04.png)

**Comment by wangzw** [comment]
We will fix this issue in next release with 500 error together.

**Comment by shubifeng** [comment]
![default](https://user-images.githubusercontent.com/6796352/35369937-b57f2f36-01c5-11e8-9a4b-a2e81551b494.png)

**Comment by jinxiaoxin** [comment]
@shubifeng 什么意思？

**Comment by shubifeng** [comment]
我也遇见同样的问题，同步单个表时正常。但200多个表时，基本不消费了，且没有任何日志。   不知道是不是机器配置太低的问题。

**Comment by jinxiaoxin** [comment]
你是maxwell--->kafka--->bireme?

**Comment by shubifeng** [comment]
是的，你的问题解决没。我这边启动就卡死，没有任何错误信息，机器只有几十MB可用估计跟这个有关。你扣扣多少，加你一起交流下。

**Comment by jinxiaoxin** [comment]
我的也没解决啊，我机器配置还可以啊，64内存，16核。你留qq我加你吧，为什么github没有私信功能。。。

**Comment by jinxiaoxin** [comment]
@shubifeng 305432835，我的qq

**Comment by shubifeng** [comment]
@jinxiaoxin 兄弟 都搞定了吗

**Comment by jinxiaoxin** [comment]
我后边自己写的同步程序

**Comment by shubifeng** [comment]
@jinxiaoxin 是在这个基础上改的吗?

**Comment by jinxiaoxin** [comment]
不是

**Comment by shubifeng** [comment]
可以共享给我吗?
